import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import Card from '../components/Card'
import Drawer from '../components/Drawer'
import styles from '../styles/Home.module.css'


const projects = [
  {
    title: "Flavorites",
    description: "Look at these full flavored functions. Woah, pizazz and all that taste."
  },
  {
    title: "Flavorites",
    description: "This is an example"
  },
  {
    title: "Flavorites",
    description: "This is an example"
  },
  {
    title: "Flavorites",
    description: "This is an example"
  }
]


export default function Home() {
  const [open, setOpen] = useState('card')

  const handleClick = () => {
    if (open === 'card') {
      console.log(open)
      setOpen("test");
    } else {
      setOpen("card");
      console.log(open)
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <button onClick={()=> handleClick()}>Open Drawer</button>
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          { projects.map((project) => {
            const testObj = {
              "card": () => ( <Card {...project} />),
              "test": () => ( <Test {...project} />),
            };
            console.log(testObj[`${open}`]);
            return testObj[`${open}`]
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
