import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import Card from '../components/Card'
import Test from '../components/Test'
import Drawer from '../components/Drawer'
import styles from '../styles/Home.module.css'


const projects = [
  {
    title: "Flavorites",
    description: "Look at these full flavored functions. Woah, pizazz and all that taste."
  },
  {
    title: "Flavorites",
    description: "This is an example"
  },
  {
    title: "Flavorites",
    description: "This is an example"
  },
  {
    title: "Flavorites",
    description: "This is an example"
  }
]


export default function Home() {
  const [open, isOpen] = useState('card')

  const testFunc = (args) => {
  const testObj = {
    test: <Test key={args.title} {...args} />,
    card: <Card key={args.title} {...args} />,
  };
    return testObj[open]
  }
  const handleClick = () => {
    if (open === 'card') {
      isOpen('test')
    } else {
      isOpen('card')
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <div className={styles.grid}>
          {projects.map((project) => {
            return testFunc(project)
          })}
        </div>
          <button onClick={()=> handleClick()}>Open Drawer</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
